@startuml
left to right direction

actor UnregisteredSupplier as "Unregistered Supplier"
actor Admin as "Administrator"
actor Dietitian
actor CentralCanteenManager as "Central Canteen Manager"


rectangle BioCantinas {

    CentralCanteenManager -- (UC1: Authenticate in the system)
    Dietitian -- (UC1: Authenticate in the system)
    Admin -- (UC1: Authenticate in the system)

    CentralCanteenManager -- (UC3: Manage my password)
    Dietitian -- (UC3: Manage my password)
    Admin -- (UC3: Manage my password)

    UnregisteredSupplier -- (UC4: Send a Supplier Application)

    Admin -- (UC5: Approve a Supplier Candidate)
    Admin -- (Visualize system logs)

    Dietitian -- (UC6: Edit proposed meal planning)
    Dietitian -- (UC7: Publish meal planning)

    CentralCanteenManager -- (UC10: Order products from suppliers)

    Admin -- (Manage supplier data)
}

@enduml