@startuml
left to right direction

actor UnregisteredSupplier as "Unregistered Supplier"
actor Admin as "Administrator"
actor Dietitian
actor CentralCanteenManager as "Central Canteen Manager"


rectangle BioCantinas {

    CentralCanteenManager -- (UC1: Authenticate in the system)
    Dietitian -- (UC1: Authenticate in the system)
    Admin -- (UC1: Authenticate in the system)

    CentralCanteenManager -- (UC2: Manage my password)
    Dietitian -- (UC3: Manage my password)
    Admin -- (UC3: Manage my password)

    UnregisteredSupplier -- (UC3: Send a Supplier Application)

    Admin -- (UC4: Approve a Supplier Candidate)

    Dietitian -- (UC5: Manage meal planning)

    CentralCanteenManager -- (UC6: Order products from suppliers)

    Admin -- (UC7: Manage supplier data)
}

@enduml