spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Database Configuration
spring.jpa.hibernate.ddl-auto=update

#Configuração SMTP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Grafana
management.endpoints.web.exposure.include=health

app.email.allowed-domains=gmail.com,outlook.com,hotmail.com,isep.ipp.pt,ipp.pt,cinfaes.pt

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

jwt.secret=${JWT_TOKEN}

virustotal.api.key=${VIRUS_TOTAL}
