spring.datasource.url=jdbc:mysql://vsgate-s1.dei.isep.ipp.pt:10422/cantinasDB
spring.datasource.username=root
spring.datasource.password=FaCm/J5xMrk+

# Database Configuration
spring.jpa.hibernate.ddl-auto=update

# Configuração SMTP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=bdb28288bf1a35
spring.mail.password=a914dbdb0aa5f9
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Grafana
management.endpoints.web.exposure.include=health,metrics,prometheus

app.email.allowed-domains=gmail.com,outlook.com,hotmail.com,isep.ipp.pt,ipp.pt,cinfaes.pt
